version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: 'develop'
    schedule:
      interval: weekly
      day: sunday
      time: '09:00'
      timezone: 'Europe/Moscow'
    labels:
      - actions
    reviewers:
      - GregoryGost
    groups:
      actions-minor:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /
    target-branch: 'develop'
    schedule:
      interval: weekly
      day: sunday
      time: '09:00'
      timezone: 'Europe/Moscow'
    labels:
      - pnpm
      - dependencies
    reviewers:
      - GregoryGost
    groups:
      development:
        dependency-type: development
        update-types:
          - minor
          - patch
      production:
        dependency-type: production
        update-types:
          - patch
