name: Develop versioning

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

permissions:
  contents: write

jobs:
  develop-version:
    if: github.event.pull_request.merged == true
    name: Develop versioning job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout step
        id: checkout
        uses: actions/checkout@v4

      - name: New tag step
        id: new-dev-version
        uses: GregoryGost/version-tagger@v1.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prefix: 'v'
          postfix: 'dev'
