name: Lint Codebase

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install pnpm
        id: setup-pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ^10

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install Dependencies
        id: pnpm-install
        run: pnpm i --frozen-lockfile

      - name: Lint Codebase
        id: super-linter
        uses: super-linter/super-linter/slim@v8.3.2
        env:
          DEFAULT_BRANCH: develop
          FILTER_REGEX_EXCLUDE: dist/**/*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # enabled
          VALIDATE_ALL_CODEBASE: true
          # disabled
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_JSCPD: false
          # for eslint 9 (flat config)
          # VALIDATE_JSON: true
          # VALIDATE_TYPESCRIPT_ES: true
          TYPESCRIPT_ES_CONFIG_FILE: eslint.config.mjs
